version: "3"
services:
  jupyter:
    image: jupyter/pyspark-notebook:678ada768ab1
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
